idf_component_register(
    SRCS
        "main.c"
        "main/attack.c"
        "wifi/attack_dos.c"
        "wifi/attack_method.c"
        "wifi/attack_handshake.c"
        "wifi/attack_pmkid.c"
        "wifi/attack_probe.c"
        "wifi/attack_deauth_detector.c"
        "wifi/attack_eviltwin.c"
        "wifi/attack_beacon_spam.c"
        "bt/bt_payload_attack.cpp"
        "bt/attack_bt_spam.c"
        "display/hydra_ssd1306_display.c"
        "utils/management_helper.c"
        "utils/wifi_pass_verifier.c"
    INCLUDE_DIRS
        "."
        "bt"
        "display"
        "main"
        "utils"
        "wifi"
        "../components"
        "../components/webserver/interface"
    REQUIRES
        ESP32-NimBLE-Keyboard
    PRIV_REQUIRES
        bt
        driver
        esp_event
        esp_http_server
        esp_netif
        esp_timer
        esp_wifi
        frame_analyzer
        hccapx_serializer
        nvs_flash
        pcap_serializer
        u8g2-hal-esp-idf
        wifi_controller
        wsl_bypasser
)
